Replace numbers with user readable text in network arch error messaages.
LeelaChessZero/lc0 pull request #1717
Opened 2022-04-01 14:04 UTC by almaudoh

2022-04-02 20:18 UTC, borg323 requested changes
You didn't change the tests in network_onnx.cc.
Also this needs to go through clang-format.

2022-04-03 19:24 UTC, masterkni6 commented on src/neural/cuda/network_cuda.cc
> +    throw Exception("Movest left head format " +
typo here?

2022-04-03 19:31 UTC, borg323 commented on src/neural/cuda/network_cuda.cc
> +    throw Exception("Movest left head format " +
Indeed it was.

2022-04-03 19:34 UTC, masterkni6 approved these changes

2022-04-03 19:57 UTC, borg323 approved these changes

2022-04-03 19:58 UTC, merged